#! /bin/sh

sxhkd &
sh ~/.config/polybar/launch.sh >> /dev/null &
sh feh --bg-fill ~/.config/wallpaper/wall.jpg &

# Single/Dual monitor config
run=1
per=10          # number of desktops per monitor

# If dual monitor use pair for one, and even for another
if [ $MONITORS -gt 1 ]; then
   for monitor in `xrandr | grep " connected " | awk '{ print$1 }'`; do
      bspc monitor $monitor -d `seq $run 2 $per`
      ((run++))
   done
else
   monitor=`xrandr | grep " connected " | awk '{ print$1 }'`
   bspc monitor $monitor -d `seq $per`
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a Android state=floating


